name: Build PS4 App Dumper

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout App Dumper
        uses: actions/checkout@v4

      - name: Build with current PS4 Payload SDK
        uses: Scene-Collective/ps4-payload-sdk@main
        with:
          app_path: .
          build_command: make

      - name: Upload App Dumper
        uses: actions/upload-artifact@v4
        with:
          name: ps4-app-dumper
          path: "*.bin"
          if-no-files-found: error
